chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
  path('', views.inbox, name='inbox'),
  path('<int:pk>/', views.chat, name='chat'),
  path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('items/', include("product.urls")),
    path('inbox/', include("chat.urls")),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
  path('', views.index, name="index"),
  path('user/items/', views.user_items, name="user_items"),
  path('contact/', views.contact, name="contact"),
  path('about/', views.about, name="about"),
  path('signup/', views.signup, name="signup"),
  path('login/', auth_views.LoginView.as_view(extra_context={"title": "Login"}, template_name='generic_form.html', authentication_form=LoginForm), name="login"),
  path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
  # Do NOT use this settings in production environment!
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browser, name='items'),
    path('new/', views.new_item, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete_item, name='delete'),
]

templates/partials/_footer.html
<footer class="footer footer-center p-10 bg-base-100 text-base-content rounded">
  <div class="grid grid-flow-col gap-4">
    <a href="{% url 'core:about' %}" class="link link-hover">About us</a> 
    <a href="{% url 'core:contact' %}" class="link link-hover">Contact</a> 
    <a href="#" class="link link-hover">Jobs</a> 
    <a href="#" class="link link-hover">Press kit</a>
  </div>     
</footer>

templates/partials/_header.html
{% load static %}

<head>
  <nav class="sticky top-0 z-30 navbar w-full px-12 bg-base-100 lg:px-36">
    <div class="flex-1">
      <a href="/" class="btn btn-ghost normal-case text-xl">
        <img src="{% static 'img/logo.png' %}" alt="Djangommerce logo" class="px-0 mx-0 h-8 w-8">
        <h1 class="text-xl font-bold bg-gradient-to-r from-cyan-500 to-green-500 bg-clip-text text-transparent">jangommerce</h1>
      </a>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'item:new' %}">New item</a></li>
        <li><a href="{% url 'item:items' %}" >Browse</a></li>
        <li>
          <details>
            <summary>
              {{ request.user.username | title }}
            </summary>
            <ul class="p-2">
              <li><a href="{% url 'chat:inbox' %}">Inbox</a></li>
              <li><a href="{% url 'core:user_items' %}">My items</a></li>
              <li><a href="{% url 'core:logout' %}">Logout</a></li>
            </ul>
          </details>
        {% else %}
        <li><a href="{% url 'item:items' %}" >Browse</a></li>
        <li><a href="{% url 'core:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
</head>