chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
  path('', views.inbox, name='inbox'),
  path('<int:pk>/', views.chat, name='chat'),
  path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('items/', include("product.urls")),
    path('inbox/', include("chat.urls")),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browser, name='items'),
    path('new/', views.new_item, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete_item, name='delete'),
]

product/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
  name = models.CharField(max_length=255)

  # Meta classes to display info about category in admin panel
  class Meta:
    ordering = ("name",)
    verbose_name_plural = "Categories"

  def __str__(self):
    return self.name

class Item(models.Model):
  AVAILABLE = "Available"
  SOLD = "Sold"
  RESERVED = "Reserved"

  STATUS_CHOICES = [
    (AVAILABLE, "Available"),
    (SOLD, "Sold"),
    (RESERVED, "Reserved")
  ]

  category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
  name = models.CharField(max_length=255)
  description = models.TextField(blank=False, null=False)
  price = models.DecimalField(max_digits=6, decimal_places=2)
  image = models.ImageField(upload_to='items', blank=True, null=True)
  status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=AVAILABLE)
  created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True, null=False)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.name

product/forms.py
from django import forms
from .models import Item

''' 
If you are using a ModelForm then there is no any need
of playing with a cleaned_data dictionary because 
when you do form.save() it is already be matched 
and the cleaned data is saved.
'''

class NewItemForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ["category", "name", "description", "price", "image"]

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields:
      inputs_attributes = {
        "class": "w-full py-4 px-6 rounded-xl border border-gray-300", 
        "placeholder": f"{str.title(field)}",  
      }
      self.fields[str(field)].widget.attrs.update(inputs_attributes)
    
    # Overwrite properties
    self.fields["category"].empty_label = "-- Click here to choose the category --"
    self.fields["description"].widget.attrs.update({
      "rows": 8
    })
    self.fields["price"].widget.attrs.update({
      "min": 0
    })
    self.fields["image"].widget.attrs.update({
      "class": "file-input file-input-bordered file-input-accent w-full",
      "required": False
    })

class EditItemForm(NewItemForm):
  class Meta(NewItemForm.Meta):
    fields = NewItemForm.Meta.fields + ["status"]
    widgets = {
      'image': forms.FileInput(attrs={
        "class": "file-input file-input-bordered file-input-accent w-full",
        "required": False
      })
    }

product/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .forms import NewItemForm, EditItemForm
from .models import Item, Category

def browser(request):
  query = request.GET.get('query', '')
  items = Item.objects.all()
  category_id = request.GET.get('category', 0)
  categories = Category.objects.all()

  if category_id:
    items = Item.objects.filter(category_id=category_id)
  if query:
    items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

  ctx = {
    "title": "Items",
    'query':query,
    "items": items,
    "categories": categories,
    "category_id": int(category_id),
  }
  return render(request, 'items.html', ctx)

def detail(request, pk):
  item = get_object_or_404(Item, pk=pk)
  related_items = Item.objects.filter(category=item.category, status=Item.AVAILABLE).exclude(pk=pk)[0:3]
  user_items = None
  if request.user.is_authenticated:
    user_items = Item.objects.filter(created_by=request.user)
  
  form = EditItemForm(instance=item)
  if request.method == "POST":
    form = EditItemForm(request.POST, request.FILES, instance=item)
    if form.is_valid:
      # No need to clean data as form uses a ModelForm
      form.save()

      return redirect('item:detail', pk=item.id)
  
  ctx = { 
    "item": item, 
    "related_items": related_items,
    "form": form, 
    "title": "Edit item",
    "user_items": user_items,
  }
  
  return render(request, "detail.html", ctx)

@login_required
def new_item(request):
  form = NewItemForm()
  if request.method == "POST":
    form = NewItemForm(request.POST, request.FILES)
    if form.is_valid:
      item = form.save(commit=False)
      item.created_by = request.user
      item.save()

      return redirect('item:detail', pk=item.id)
  
  ctx = { "form": form, "title": "New item" }
  return render(request, "generic_form.html", ctx)

@login_required
def delete_item(request, pk):
  user = request.user
  item = get_object_or_404(Item, pk=pk, created_by=user)
  item.delete()

  return redirect("core:user_items")

product/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if request.user == item.created_by %}
{{ title }}
{% else %}
{{ item.name }}
{% endif %}
{% endblock %}

{% block content %}
<!-- Selected item content -->
<section class="grid grid-cols-5 gap-6">
  <!-- Render image -->
  <div class="col-span-3 bg-base-200 rounded-xl">
    {% if item.image %}
    <img src="{{ item.image.url }}" alt="{{ item.image }}" class="rounded-xl">
    {% else %}
    <img src="https://placehold.co/1280x853?text=Djangommerce" class="rounded-xl">
    {% endif %}

    <!-- Render items details before changes by user -->
    {% if request.user == item.created_by %}
    <div class="p-8">
      <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
      <p class="py-0.5"><strong class="text-gray-600">Price: </strong>{{ item.price }}</p>
      <p class="py-0.5"><strong class="text-gray-600">Status: </strong>{{ item.status }}</p>
      <p class="py-0.5"><strong class="text-gray-600">Seller: </strong>{{ item.created_by.username }}</p>

      {% if item.description %}
      <p>
        <strong class="py-0.5 text-gray-600">Description:</strong>
        {{ item.description }}
      </p>
      {% endif %}
    </div>
    {% endif %}

  </div>

  <!-- Render form -->
  <div class="col-span-2 p-6 bg-base-200 rounded-xl">

    {% if request.user == item.created_by %}
    <h1 class="mb-6 text-3xl text-center">{{ title }}</h1>
    <form id="form" method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}

      <!-- Display form fields -->
      {% for field in form %}
      <div class="mb-3 p-2">{{ field }}</div>
      {% endfor %}

      <!-- Display error if any -->
      {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}
        {{ form.non_field_errors }}
      </div>
      {% endif %}
      <button id="form-submit"
        class="block mb-3 w-full py-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
      <a href="{% url 'item:delete' item.id %}"
        class="block mx-auto w-full py-4 text-lg bg-red-400 hover:bg-red-600 rounded-xl text-center text-white">Delete</a>
    </form>

    {% else %}
    <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
    <p class="py-0.5 text-gray-600"><strong>Price: </strong>{{ item.price }}</p>
    <p class="py-0.5 text-gray-600"><strong>Status: </strong>{{ item.status }}</p>
    <p class="py-0.5 text-gray-600"><strong>Seller: </strong>{{ item.created_by.username }}</p>

    {% if item.description %}
    <p class="py-0.5 text-gray-700">
      <strong class="py-0.5 text-gray-600">Description:</strong>
      {{ item.description }}
    </p>
    {% endif %}

    <a href="{% url 'chat:new' item.id %}"
      class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact
      seller</a>
    {% endif %}
  </div>
</section>

<!-- Related items / More of your items box  -->
<section class="mt-6 px-6 py-12 bg-base-200 rounded-xl">
  {% if request.user == item.created_by %}
  <h1 class="mb-6 text-3xl text-center">More of your items</h1>
  <div class="grid grid-cols-3 gap-3">
    {% for item in user_items %}
    <div class="card bg-base-100 shadow-xl">
      <a href="{% url 'item:detail' item.id %}">
        <figure>
          {% if item.image %}
          <img src="{{ item.image.url }}" alt="{{ item.image }}" class="rounded-t-xl object-cover h-52 w-full" loading="lazy">
          {% else %}
          <img src="https://placehold.co/1080x1280?text=Djangommerce" class="rounded-t-xl object-cover h-52 w-full" alt="No image">
          {% endif %}
        </figure>
        <div class="card-body">
          <h2 class="card-title">{{ item.name }}</h2>
          <p>Price: {{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>

  {% else %}
  <h2 class="mb-12 text-2xl text-center">Related items</h2>

  <div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
    <div class="card bg-base-100 shadow-xl">
      <a href="{% url 'item:detail' item.id %}">
        <figure>
          {% if item.image %}
          <img src="{{ item.image.url }}" alt="{{ item.image }}" class="rounded-t-xl object-cover h-52 w-full" loading="lazy">
          {% else %}
          <img src="https://placehold.co/1280x853?text=Djangommerce" class="rounded-t-xl object-cover h-52 w-full" alt="No image">
          {% endif %}
        </figure>
        <div class="card-body">
          <h2 class="card-title">{{ item.name }}</h2>
          <p>Price: {{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  {% endif %}
</section>
{% endblock %}

product/templates/items.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<div class="grid grid-cols-4 gap-4">
  <div class="p-6 col-span-1 bg-base-200 rounded-xl">

    <!-- Filter by category -->
    <div class="mb-4">
      <p class="mb-4 font-semibold text-center">Categories:</p>
      <ul>
        {% for category in categories %}
        <li class="py-2 px-2 text-center rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
          <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>

    <!-- Filter text input -->
    <form method="get" action="{% url 'item:items' %}">
      <input name="query" class="block mb-3 w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}"
        placeholder="Filter by...">
      <button class="block mb-3 w-full py-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Search</button>
    </form>
    
    <a href="{% url 'item:items' %}"
      class="mb-3 py-4 w-full block text-lg rounded-xl text-white text-center bg-yellow-500 hover:bg-yellow-700">Clear
      filters</a>
  </div>

  <div class="col-span-3 px-6 py-8 bg-base-200 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">
      {% if query|length > 20 %}
      <!-- Query calling length method. In python code: length(query)-->
      Try with a shorter text
      {% elif query and not items %}
      No results for "{{ query }}"
      {% elif query and items %}
      Results for "{{ query }}"
      {% else %}
      Available items
      {% endif %}
    </h2>

    <div class="grid grid-cols-3 lg:grid-cols-4 gap-3">
      {% for item in items %}
      <div class="card bg-base-100 shadow-xl">
        <a href="{% url 'item:detail' item.id %}">
          <figure>
            {% if item.image %}
            <img src="{{ item.image.url }}" alt="{{ item.image }}" class="rounded-t-xl object-cover h-52 w-full"
              loading="lazy">
            {% else %}
            <img src="https://placehold.co/520x960?text=Djangommerce" class="rounded-t-xl object-cover h-52 w-full"
              alt="No image">
            {% endif %}
          </figure>
          <div class="card-body">
            <h2 class="card-title">{{ item.name }}</h2>
            <p>Price: {{ item.price }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

product/templates/user_items.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<section class="px-6 py-8 bg-base-200 rounded-xl">
  <h1 class="mb-12 text-2xl text-center">{{ title }}</h1>

  <div class="grid grid-cols-3 gap-3">
    {% for item in items %}
    <div class="card bg-base-100 shadow-xl">
      <a href="{% url 'item:detail' item.id %}">
        <figure>
          {% if item.image %}
          <img src="{{ item.image.url }}" alt="{{ item.image }}" class="rounded-t-xl object-cover h-52 w-full" loading="lazy">
          {% else %}
          <img src="https://placehold.co/520x960?text=Djangommerce" class="rounded-t-xl object-cover h-52 w-full" alt="No image">
          {% endif %}
        </figure>
        <div class="card-body">
          <h2 class="card-title">{{ item.name }}</h2>
          <p>Price: {{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}