chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
  path('', views.inbox, name='inbox'),
  path('<int:pk>/', views.chat, name='chat'),
  path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('items/', include("product.urls")),
    path('inbox/', include("chat.urls")),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
  path('', views.index, name="index"),
  path('user/items/', views.user_items, name="user_items"),
  path('contact/', views.contact, name="contact"),
  path('about/', views.about, name="about"),
  path('signup/', views.signup, name="signup"),
  path('login/', auth_views.LoginView.as_view(extra_context={"title": "Login"}, template_name='generic_form.html', authentication_form=LoginForm), name="login"),
  path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
  # Do NOT use this settings in production environment!
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browser, name='items'),
    path('new/', views.new_item, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete_item, name='delete'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock %}
{% block content %}
<section>
  <!-- About Djangommerce -->
  <div class="my-6 hero py-14 bg-base-200 rounded-xl">
    <div class="hero-content text-center">
      <div class="max-w-md">
        <h1 class="py-2 text-5xl font-bold bg-gradient-to-r from-cyan-500 to-green-500 bg-clip-text text-transparent">
          Djangommerce</h1>
        <p class="py-6">
          This is an online market hub built using Django and Tailwind CSS with DaisyUI components, designed to allow
          you to post items for sale and find potential buyers!
        </p>
        <a href="{% url 'core:signup' %}" class="btn btn-primary">Join us now!</a>
      </div>
    </div>
  </div>

  <!-- Credit for the logo/icon -->
  <div class="card w-96 bg-base-200">
    <div class="card-body items-center text-center">
      <h2 class="card-title">Credits</h2>
      <p>
        Letter D icon created by shohanur.rahman13
        <a href="https://www.flaticon.com/free-icons/letter-d" title="letter d icons" target="_blank"
          rel="noopener noreferrer"> - Flaticon</a>
      </p>
      <p>
        Djangommerce image placeholder
        <a href="https://placehold.co" title="placehold" target="_blank" rel="noopener noreferrer"> - Placehold</a>
      </p>
    </div>
  </div>
</section>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% block title %}{% endblock %} | Djangommerce</title>
  <meta name="description" content="A brief description" />
  <meta name="author" content="Djangommerce is an ecommerce project build with Django" />
  <link rel="shortcut icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
  <!-- Daisy UI -->
  <link href="https://cdn.jsdelivr.net/npm/daisyui@3.5.1/dist/full.css" rel="stylesheet" type="text/css" />
</head>

<body class="bg-base-300">
  <!-- Header content -->
  {% include 'partials/_header.html' %}

  <!-- Main content from apps -->
  <main class="px-12 py-12 lg:px-36">
    {% block content %} {% endblock %}
  </main>

  <!--Footer content-->
  {% include 'partials/_footer.html' %}

  <script src="https://cdn.tailwindcss.com"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<div class="my-6 hero py-14 bg-base-200 rounded-xl">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="py-2 text-5xl font-bold bg-gradient-to-r from-cyan-500 to-green-500 bg-clip-text text-transparent">{{ title }}, {{ username }}!</h1>
      <p class="py-6">
        We are happy to know your opinion about Djangommerce, and will get back to you as soon as possible.
      </p>
      <a href="{% url 'core:signup' %}" class="btn btn-primary">Join us now!</a>
    </div>
  </div>
</div>
{% endblock %}

templates/generic_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<div class="w-4/5 my-6 mx-auto p-6 bg-base-200 rounded-xl">
  <h1 class="mb-6 text-3xl text-center">{{ title }}</h1>

  <form id="form" method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <!-- Display form fields -->
    {% for field in form %}
    <div class="mb-3 p-2">{{ field }}</div>
    {% endfor %}

    <!-- Display error if any -->
    {% if form.errors or form.non_field_errors %}
    <div class="alert alert-error mb-3 p-6">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span>
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
      </span>
    </div>
    {% endif %}

    <button id="form-submit"
      class="block mx-auto w-full py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
  </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome{% endblock %}
{% block content %}

<!-- Welcome message -->
<div class="my-6 hero py-14 bg-base-200 rounded-xl">
  <div class="hero-content text-center">
    <div class="max-w-md">
      {% if request.user.is_authenticated %}
      <h4 class="text-5xl font-bold">Welcome back, {{ request.user.username | title }}!</h4>
      {% else %}
      <h1 class="text-5xl font-bold">Hello there 👋</h1>
      <p class="py-6">
        <span class="text-xl inline font-bold bg-gradient-to-r from-cyan-500 to-green-500 bg-clip-text text-transparent">Djangommerce</span>
        is an online market hub built using Django and Tailwind CSS with DaisyUI components, designed to allow you to post items for sale and find potential buyers!
      </p>
      <a href="{% url 'core:signup' %}" class="btn btn-primary">Join us now!</a>
      {% endif %}
    </div>
  </div>
</div>

<!--Gallery container -->
<div class="px-6 py-8 bg-base-200 rounded-xl">
  {% if request.user.is_authenticated %}
  <h2 class="mb-12 text-2xl text-center">You might find interesting</h2>
  {% else %}
  <h2 class="mb-12 text-2xl text-center">New items</h2>
  {% endif %}
  <!-- Items gallery -->
  <div class="grid grid-cols-3 lg:grid-cols-5 gap-3">
    {% for item in items %}
    <div class="card bg-base-100 shadow-xl">
      <a href="{% url 'item:detail' item.id %}">
        <figure>
          {% if item.image %}
          <img src="{{ item.image.url }}" alt="{{ item.image }}" class="h-52 w-full object-cover rounded-t-xl" loading="lazy">
          {% else %}
          <img src="https://placehold.co/520x960?text=Djangommerce" alt="No image" class="h-52 w-full object-cover rounded-t-xl">
          {% endif %}
        </figure>
        <div class="card-body">
          <h2 class="card-title">{{ item.name }}</h2>
          <p>Price: {{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<!-- Categories section -->
<div class="mt-6 px-6 py-6 bg-base-200 rounded-xl">
  <h2 class="mb-10 text-2xl text-center">Categories</h2>

  <div class="grid grid-cols-3 gap-3 lg:grid-cols-4">
    {% for category in categories %}
    <div>
      <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
        <div class="card card-body bg-base-100 shadow-xl">
          <h2 class="text-2xl">{{ category.name }}</h2>
          <p class="text-gray-500">{{ category.items.count }} items</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}